---
- name: Install the registry dependency
  package:
    name:
      - docker
      - python-docker-py
      - docker-distribution
  become: True

- name: Prepare docker configuration
  copy:
    content: |
      {"insecure-registries":["{{ dci_sync_registry_local_ip }}:{{ dci_sync_registry_local_port }}"] }
    dest: /etc/docker/daemon.json
  become: True

- name: Enable overlay2 storage backend
  lineinfile:
    dest: /etc/sysconfig/docker-storage-setup
    line: "STORAGE_DRIVER=overlay2"
    regexp: '^STORAGE_DRIVER='
  become: True

- name: Create the docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: Create the http-proxy configuration for systemd
  template:
    src: docker_http_proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  become: True

- name: Ensure docker is restarted
  service:
    # we reload systemd in case docker.service.d content has changed
    daemon_reload: True
    name: docker
    state: restarted
  become: True

- name: Prepare docker-distribution configuration
  template:
    src: docker_distribution.yml.j2
    dest: /etc/docker-distribution/registry/config.yml
  become: True

- name: Ensure docker-distribution is restarted
  service:
    name: docker-distribution
    state: restarted
  become: True

- name: Open docker registry port on the firewall
  firewalld:
    zone: public
    port: '{{ dci_sync_registry_local_port }}/tcp'
    permanent: true
    state: enabled
  register: result
  failed_when: false
  become: true

- name: Skip container images from list
  lineinfile:
    path: '{{ dci_sync_registry_images_list }}'
    regexp: '.*-{{ item }}.*'
    state: absent
  with_items: '{{ dci_sync_registry_skip_list }}'

- name: Download the Openstack container images
  shell: |
    python ./fetch_images.py {{ dci_sync_registry_images_list }}
  args:
    chdir: '{{ role_path }}/files'
  register: image_sync_result
  until: image_sync_result.rc == 0
  retries: 3
  delay: 60
  become: True
  become_flags: '-E'
  environment:
    DCI_REGISTRY: '{{ dci_sync_registry_remote_url }}'
    DCI_REGISTRY_PASSWORD: '{{ dci_sync_registry_remote_password }}'
    DCI_REGISTRY_USER: '{{ dci_sync_registry_remote_login }}'
