---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: el7
    image: centos/systemd:latest
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
