---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint tasks
platforms:
  - name: el7
    image: centos/systemd:latest
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - destroy
verifier:
  name: testinfra
  options:
    verbosity: 1
  lint:
    name: flake8
