---
- name: Converge
  hosts: all
  tasks:
    - include_role:
        name: ansible-role-dci-sync-registry
      vars:
        dci_sync_registry_images_list: /var/tmp/images_list.yaml
        dci_sync_registry_local_ip: 127.0.0.1
        dci_sync_registry_skip_list: ['httpd']
        dci_sync_registry_storage: vfs
